export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const TOGGLE_COMPLETE_TASK = 'TOGGLE_COMPLETE_TASK';
export const TOGGLE_COMPLETE_TASK_SUCCESS = 'TOGGLE_TASK_SUCCESS';
export const TOGGLE_COMPLETE_TASK_FAILURE = 'TOGGLE_TASK_FAILURE';

export const REORDER_TASKS = 'REORDER_TASKS';
export const REORDER_TASKS_SUCCESS = 'REORDER_TASKS_SUCCESS';
export const REORDER_TASKS_FAILURE = 'REORDER_TASKS_FAILURE';
